# To install/reinstall the environment:
#   conda-env create -f conda.install.yml
#
# name: sds2022
channels:
  - conda-forge
  - defaults
dependencies:
  - pip 
  - black # Supports code formatter labextension
  - catboost
  - clustergram
  - contextily 
  - cmake<3.20
  - dash
  - descartes
  - feather-format 
  - gensim 
  - geopandas
  - geopy 
  - hdbscan
  - icecream
  - ipyleaflet 
  - ipympl 
  - ipyparallel 
  - ipywidgets 
  - jupyter_bokeh
  - jupyterlab_code_formatter # Supports labextension
  - jupyter-dash # Plotly support
  - jupyterlab-geojson
  - jupyterlab-variableinspector
  - jupyter-lsp-python # Provides LSP Extension + Server
  - legendgram 
  - mkl-service 
  - momepy
  - nbdime 
  - networkx 
  - nltk 
  - numba
  - osmnx
  - palettable 
  - pointpats
  - polyline
  - plotly
  - psycopg2
  - pygeos
  - pymc3
  - pykrige
  - pysal
  - qgrid 
  - rasterio 
  - rasterstats 
  - scipy
  - seaborn
  - spacy 
  - spacy[transformer] 
  - tabulate  # For exporting from pandas to markdown
  - textblob 
  - tzlocal 
  - umap-learn
  - openpyxl
  - xlsxwriter
  - pip:
    - boruta # Supports feature selection
    - contractions 
    - dtreeviz
    - dtreeviz[xgboost]
    - geofeather 
    #- git+https://github.com/smazzanti/mrmr # Supports feature selection
    #- git+http://github.com/kingsgeocomp/SOMPY#egg=sompy
    - joypy
    - jupytext
    - kneed
    - langdetect
    - lightgbm 
    - matplotlib-scalebar 
    - mgwr
    - num2words
    - scikit-posthocs
    - smopy # NOT a typo! Not the same thing as sompy!
    - top2vec
    - unidecode
    - wordcloud
    - xgboost
