# To install/reinstall the environment:
#   conda-env create -f conda.install.yml
#
# name: sds2022
channels:
  - conda-forge
  - defaults
dependencies:
  - pip 
  #- altair
  - black # Supports code formatter labextension
  #- bokeh
  - catboost
  - clustergram
  - contextily 
  #- cmake<3.20
  #- dash
  - descartes
  - gensim 
  - geopandas
  - geopy 
  - hdbscan
  - icecream
  - ipyleaflet 
  - ipyparallel 
  - jupyter_bokeh
  - jupyterlab_code_formatter # Supports labextension
  - jupyterlab-geojson
  - jupyterlab-variableinspector
  - jupyter-lsp-python # Provides LSP Extension + Server
  - legendgram 
  - lxml
  #- mkl-service
  - mgwr 
  - momepy
  #- nbdime 
  #- networkx 
  - nltk 
  #- numba
  - openpyxl
  - osmnx
  - palettable 
  - pointpats
  - polars
  - polyline
  - plotly
  #- psycopg2
  #- pygeos # Not needed with Shapely2 and Geopandas
  #- pymc3
  - pyogrio
  - pysal
  #- qgrid 
  - rasterio 
  - rasterstats 
  - shap
  - spacy 
#  - spacy[transformer] 
  - spopt
  - tabulate  # For exporting from pandas to markdown
  - textblob 
  - tzlocal 
  - umap-learn
  - xlsxwriter
  - ydata-profiling
  - pip:
    - boruta # Supports feature selection
    - contractions 
    - dtreeviz
    - dtreeviz[xgboost]
    - duckdb
    - esda # (alternative to PySAL stuff)
    - fastai #==1.0.61 # Huanfa's QM
    - gurobipy #==9.5.1 # Huanfa's QM
    #- git+https://github.com/smazzanti/mrmr # Supports feature selection
    #- git+http://github.com/kingsgeocomp/SOMPY#egg=sompy
    - joypy
    - jupyterlab-quarto
    - jupytext
    - kneed
    - langdetect
    - libpysal
    - lightgbm 
    - matplotlib-scalebar 
    - mgwr
    #- mpl_toolkits
    - num2words
    - pulp #==2.6.0 # Huanfa's QM
    - pykrige # Might not be available for Apple Silicon
    - rfpimp
    - scikit-posthocs
    - skimpy
    - sklearn-som
    - smopy # NOT a typo! Not the same thing as sompy!
    #- text_to_num
    - tldr  # Useful replacement for man
    - top2vec
    - unidecode
    - wordcloud
    - xgboost
