# To install/reinstall the environment:
#   conda-env create -f conda.install.yml
#
# name: sds2022
channels:
  - conda-forge
  - defaults
dependencies:
  - pip 
  #- altair
  - black # Supports code formatter labextension
  #- bokeh
  - catboost
  - clustergram
  - contextily 
  - cmake<3.20
  - dash
  - descartes
  - feather-format 
  - gensim 
  - geopandas
  - geopy 
  - hdbscan
  - icecream
  - ipyleaflet 
  - ipympl 
  - ipyparallel 
  - ipywidgets 
  - jupyter_bokeh
  - jupyterlab_code_formatter # Supports labextension
  - jupyter-dash # Plotly support
  - jupyterlab-geojson
  - jupyterlab-variableinspector
  - jupyter-lsp-python # Provides LSP Extension + Server
  - legendgram 
  - lxml
  #- mkl-service
  - mgwr 
  - momepy
  - nbdime 
  #- networkx 
  - nltk 
  #- numba
  - osmnx
  - palettable 
  #- pandas-profiling
  - pointpats
  - polars
  - polyline
  - plotly
  - psycopg2
  #- pygeos # Not needed with Shapely2 and Geopandas
  #- pymc3
  - pykrige
  - pysal
  #- qgrid 
  - rasterio 
  - rasterstats 
  - scipy
  - shap
  - seaborn
  - spacy 
  - spacy[transformer] 
  - spopt
  - tabulate  # For exporting from pandas to markdown
  - textblob 
  - tzlocal 
  - umap-learn
  - openpyxl
  - xlsxwriter
  - pip:
    - boruta # Supports feature selection
    - contractions 
    - dtreeviz
    - dtreeviz[xgboost]
    - duckdb
    - fastai==1.0.61 # Huanfa's QM
    - geofeather 
    - gurobipy==9.5.1 # Huanfa's QM
    #- git+https://github.com/smazzanti/mrmr # Supports feature selection
    #- git+http://github.com/kingsgeocomp/SOMPY#egg=sompy
    - joypy
    - jupytext
    - kneed
    - langdetect
    - lightgbm 
    - matplotlib-scalebar 
    - mgwr
    - num2words
    - pulp==2.6.0 # Huanfa's QM
    - rfpimp
    - scikit-posthocs
    - skimpy
    - sklearn-som
    - smopy # NOT a typo! Not the same thing as sompy!
    - text_to_num
    - top2vec
    - unidecode
    - wordcloud
    - xgboost
