name: sds2020
channels:
  - conda-forge
  - defaults
dependencies:
  - access=1.1.1
  - affine=2.3.0
  - appdirs=1.4.3
  - argon2-cffi=20.1.0
  - astroid=2.4.2
  - attrs=20.2.0
  - autopep8=1.5.4
  - backcall=0.2.0
  - beautifulsoup4=4.9.1
  - black=20.8b1
  - bleach=3.1.5
  - blosc=1.20.1
  - bokeh=2.2.1
  - branca=0.3.1
  - brotli=1.0.9
  - brunsli=0.1
  - bs4=4.9.1
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - catalogue=1.0.0
  - certifi=2020.6.20
  - cffi=1.14.1
  - cfitsio=3.470
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.6.0
  - cmake=3.18.2
  - colorama=0.4.3
  - contextily=1.0.0
  - coverage=5.2.1
  - cryptography=3.1
  - curl=7.71.1
  - cycler=0.10.0
  - cymem=2.0.3
  - cython=0.29.21
  - cython-blis=0.4.1
  - cytoolz=0.10.1
  - dask-core=2.25.0
  - dataclasses=0.7
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - dnspython=2.0.0
  - entrypoints=0.3
  - esda=2.3.1
  - expat=2.2.9
  - fastcache=1.1.0
  - feather-format=0.4.1
  - fiona=1.8.13
  - flake8=3.8.3
  - folium=0.11.0
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - future=0.18.2
  - gdal=3.0.4
  - geographiclib=1.50
  - geopandas=0.8.1
  - geopy=2.0.0
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giddy=2.3.3
  - giflib=5.2.1
  - gitdb=4.0.5
  - gitpython=3.1.8
  - glib=2.65.0
  - glog=0.4.0
  - gmp=6.2.0
  - gmpy2=2.1.0b1
  - hdbscan=0.8.26
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=64.2
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - inequality=1.0.0
  - iniconfig=1.0.1
  - ipykernel=5.3.4
  - ipyleaflet=0.13.3
  - ipympl=0.5.7
  - ipyparallel=6.3.0
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9d
  - json-c=0.13.1
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab=2.2.7
  - jupyterlab_code_formatter=1.3.6
  - jupyterlab_server=1.2.0
  - jxrlib=1.1
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - legendgram=0.0.3
  - lerc=2.2
  - llvm-openmp=10.0.1
  - llvmlite=0.34.0
  - lz4-c=1.9.2
  - lzo=2.10
  - mapclassify=2.3.0
  - markupsafe=1.1.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mercantile=1.1.6
  - mgwr=2.1.1
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mock=4.0.2
  - more-itertools=8.5.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - munch=2.5.0
  - murmurhash=1.0.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.21
  - mysql-connector-python=8.0.21
  - mysql-libs=8.0.21
  - nbconvert=5.6.1
  - nbdime=2.0.0
  - nbformat=5.0.7
  - ncurses=6.2
  - networkx=2.5
  - nltk=3.4.4
  - nodejs=13.13.0
  - nose=1.3.7
  - notebook=6.1.3
  - numba=0.51.2
  - numexpr=2.7.1
  - numpy=1.19.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - osmnx=0.16.0
  - packaging=20.4
  - palettable=3.3.0
  - pandana=0.5.1
  - pandas=1.1.2
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.1
  - pathspec=0.8.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.3
  - pixman=0.38.0
  - plac=0.9.6
  - pluggy=0.13.1
  - pointpats=2.2.0
  - polyline=1.4.0
  - poppler=0.87.0
  - poppler-data=0.4.9
  - postgresql=12.3
  - preshed=3.0.2
  - proj=7.0.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - protobuf=3.12.4
  - psycopg2=2.8.6
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.9.0
  - pyarrow=1.0.1
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygeos=0.8
  - pygments=2.6.1
  - pykrige=1.5.1
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyrsistent=0.16.0
  - pysal=2.3.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.0.1
  - pytest-cov=2.10.1
  - python=3.7.8
  - python-dateutil=2.8.0
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.34.1
  - python_abi=3.7
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qgrid=1.3.1
  - quantecon=0.4.8
  - rasterio=1.1.5
  - rasterstats=0.14.0
  - re2=2020.08.01
  - readline=8.0
  - regex=2020.7.14
  - requests=2.24.0
  - rhash=1.3.6
  - rope=0.17.0
  - rtree=0.9.4
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - segregation=1.3.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - simplejson=3.17.2
  - six=1.15.0
  - smmap=3.0.4
  - snappy=1.1.8
  - snowballstemmer=2.0.0
  - snuggs=1.4.7
  - soupsieve=2.0.1
  - spacy=2.3.2
  - spaghetti=1.5.0
  - spglm=1.0.7
  - spint=1.0.6
  - splot=1.1.3
  - spreg=1.1.2.post1
  - spvcm=0.3.0
  - sqlalchemy=1.3.19
  - sqlite=3.33.0
  - srsly=1.0.2
  - statsmodels=0.12.0
  - sympy=1.6.2
  - tabulate=0.8.7
  - tbb=2020.2
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.4.1
  - threadpoolctl=2.1.0
  - tifffile=2020.9.3
  - tiledb=1.7.7
  - tobler=0.4.0
  - toml=0.10.1
  - toolz=0.10.0
  - tornado=6.0.4
  - tqdm=4.48.2
  - traitlets=4.3.3
  - traittypes=0.2.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - tzcode=2020a
  - tzlocal=2.1
  - ujson=1.35
  - urllib3=1.24.3
  - wasabi=0.7.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xlsxwriter=1.3.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.2
  - zfp=0.5.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - jupyter-lsp==0.9.2
    - jupyterlab-gitplus==0.1.15
    - multicoretsne==0.1
    - scikit-posthocs==0.6.5
    - smopy==0.0.7
    - git+http://github.com/kingsgeocomp/SOMPY#egg=sompy
    - wordcloud==1.8.0
