Executing the command: conda env export -n base
name: base
channels:
  - defaults
  - pyviz
  - conda-forge
dependencies:
  - access=1.1.7
  - affine=2.3.1
  - alembic=1.7.6
  - altair=4.2.0
  - amply=0.1.5
  - ansi2html=1.7.0
  - anyio=3.5.0
  - aom=3.3.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arviz=0.11.2
  - astroid=2.5.6
  - asttokens=2.0.5
  - async_generator=1.10
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - autopep8=1.5.7
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.10.0
  - binutils=2.36.1
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - black=22.3.0
  - blas=2.113
  - blas-devel=3.9.0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.0
  - bokeh=2.4.2
  - bottleneck=1.3.4
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.0.4
  - c-compiler=1.4.2
  - ca-certificates=2022.5.18.1
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - cairo=1.16.0
  - catalogue=2.0.6
  - catboost=1.0.6
  - certifi=2021.10.8
  - certipy=0.1.3
  - cffi=1.15.0
  - cfitsio=4.0.0
  - cftime=1.6.0
  - charls=2.3.4
  - charset-normalizer=2.0.12
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - clustergram=0.6.0
  - cmake=3.19.4
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.6
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - colorama=0.4.4
  - conda=4.11.0
  - conda-package-handling=1.7.3
  - configurable-http-proxy=4.5.1
  - contextily=1.2.0
  - cryptography=36.0.1
  - curl=7.81.0
  - cxx-compiler=1.4.2
  - cycler=0.11.0
  - cymem=2.0.6
  - cython=0.29.28
  - cython-blis=0.7.7
  - cytoolz=0.11.2
  - dash=2.4.1
  - dask=2022.2.1
  - dask-core=2022.2.1
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecat=2.1.1
  - deprecation=2.1.0
  - descartes=1.1.0
  - dill=0.3.4
  - distributed=2022.2.1
  - docutils=0.18.1
  - entrypoints=0.4
  - esda=2.4.1
  - et_xmlfile=1.0.1
  - executing=0.8.3
  - expat=2.4.8
  - fastprogress=1.0.2
  - feather-format=0.4.1
  - filelock=3.7.1
  - fiona=1.8.21
  - flake8=3.9.2
  - flask=2.1.2
  - flask-compress=1.12
  - flit-core=3.7.1
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.29.1
  - freetype=2.10.4
  - freexl=1.0.6
  - fribidi=1.0.10
  - fsspec=2022.2.0
  - gcc=10.3.0
  - gcc_impl_linux-64=10.3.0
  - gcc_linux-64=10.3.0
  - gdal=3.4.2
  - gdk-pixbuf=2.42.8
  - gensim=4.2.0
  - geographiclib=1.52
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geopy=2.2.0
  - geos=3.10.2
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giddy=2.3.3
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - graphite2=1.3.13
  - graphviz=3.0.0
  - greenlet=1.1.2
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx=10.3.0
  - gxx_impl_linux-64=10.3.0
  - gxx_linux-64=10.3.0
  - h5py=3.6.0
  - harfbuzz=4.2.0
  - hdbscan=0.8.28
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icecream=2.1.2
  - icu=69.1
  - idna=3.3
  - imagecodecs=2022.2.22
  - imageio=2.16.1
  - importlib-metadata=4.11.2
  - importlib_metadata=4.11.2
  - importlib_resources=5.4.0
  - inequality=1.0.0
  - ipykernel=6.9.1
  - ipyleaflet=0.16.0
  - ipympl=0.9.1
  - ipyparallel=8.3.0
  - ipython=8.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - isort=5.10.1
  - itsdangerous=2.1.2
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter-dash=0.4.2
  - jupyter-lsp=1.5.1
  - jupyter-lsp-python=1.5.1
  - jupyter-server-mathjax=0.2.5
  - jupyter_bokeh=3.0.4
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyter_telemetry=0.1.0
  - jupyterhub=2.1.1
  - jupyterhub-base=2.1.1
  - jupyterlab=3.3.0
  - jupyterlab-geojson=3.2.0
  - jupyterlab-variableinspector=3.0.9
  - jupyterlab_code_formatter=1.4.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.2
  - jxrlib=1.1
  - kealib=1.4.14
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - langcodes=3.3.0
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - legendgram=0.0.3
  - lerc=3.0
  - llvm-openmp=13.0.1
  - llvmlite=0.38.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mako=1.1.6
  - mamba=0.22.1
  - mapclassify=2.4.3
  - markupsafe=2.1.0
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mercantile=1.2.1
  - mgwr=2.1.2
  - mistune=0.8.4
  - mkl=2022.0.1
  - mkl-service=2.4.0
  - momepy=0.5.3
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - msgpack-python=1.0.3
  - munch=2.5.0
  - munkres=1.1.4
  - murmurhash=1.0.7
  - mypy_extensions=0.4.3
  - nbclassic=0.3.5
  - nbclient=0.5.11
  - nbconvert=6.4.2
  - nbdime=3.1.1
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - netcdf4=1.5.8
  - networkx=2.8.2
  - nltk=3.6.7
  - nodejs=17.4.0
  - nomkl=3.0
  - nose=1.3.7
  - notebook=6.4.8
  - nspr=4.32
  - nss=3.78
  - numba=0.55.1
  - numexpr=2.8.0
  - numpy=1.21.5
  - oauthlib=3.2.0
  - openblas=0.3.18
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1o
  - orc=1.7.3
  - osmnx=1.2.0
  - packaging=21.3
  - palettable=3.3.0
  - pamela=1.0.0
  - pandas=1.4.1
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.9.0
  - pathy=0.6.1
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.1.2
  - pixman=0.40.0
  - platformdirs=2.5.1
  - plotly=5.8.0
  - pluggy=1.0.0
  - pointpats=2.2.0
  - polyline=1.4.0
  - poppler=22.01.0
  - poppler-data=0.4.11
  - postgresql=14.2
  - preshed=3.0.6
  - proj=9.0.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.27
  - protobuf=3.19.4
  - psutil=5.9.0
  - psycopg2=2.9.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.6.0
  - pure_eval=0.2.2
  - pyarrow=7.0.0
  - pybind11-abi=4
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pycurl=7.44.1
  - pydantic=1.8.2
  - pydocstyle=6.1.1
  - pyflakes=2.3.1
  - pygeos=0.12.0
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pykrige=1.6.1
  - pylint=2.8.3
  - pymc3=3.11.5
  - pynndescent=0.5.7
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyproj=3.3.1
  - pyrsistent=0.18.1
  - pysal=2.6.0
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.9.10
  - python-dateutil=2.8.2
  - python-graphviz=0.20
  - python-json-logger=2.0.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-tzdata=2022.1
  - python_abi=3.9
  - pytz=2021.3
  - pytz-deprecation-shim=0.1.0.post0
  - pywavelets=1.2.0
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qgrid=1.3.1
  - quantecon=0.5.2
  - rasterio=1.2.10
  - rasterstats=0.16.0
  - re2=2022.02.01
  - readline=8.1
  - regex=2022.4.24
  - reproc=14.2.3
  - requests=2.27.1
  - retrying=1.3.3
  - rhash=1.4.1
  - rope=1.1.1
  - rtree=1.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.15.80
  - rvlib=0.0.6
  - s2n=1.0.10
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - segregation=2.1.0
  - semver=2.13.0
  - send2trash=1.8.0
  - setuptools=59.8.0
  - shapely=1.8.2
  - shellingham=1.4.0
  - simplejson=3.17.6
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=3.0.5
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - spacy=3.3.0
  - spacy-legacy=3.0.9
  - spacy-loggers=1.0.2
  - spaghetti=1.6.5
  - spglm=1.0.8
  - spint=1.0.7
  - splot=1.1.5.post1
  - spopt=0.4.0
  - spreg=1.2.4
  - spvcm=0.3.0
  - sqlalchemy=1.4.31
  - sqlite=3.38.5
  - srsly=2.4.3
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - sympy=1.9
  - sysroot_linux-64=2.12
  - tabulate=0.8.9
  - tbb=2021.5.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.13.2
  - testpath=0.6.0
  - textblob=0.15.3
  - theano-pymc=1.1.2
  - thinc=8.0.15
  - threadpoolctl=3.1.0
  - tifffile=2022.2.9
  - tiledb=2.7.1
  - tobler=0.9.0
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - traittypes=0.2.1
  - typed-ast=1.5.4
  - typer=0.4.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzcode=2022a
  - tzdata=2021e
  - tzlocal=4.2
  - ujson=5.3.0
  - umap-learn=0.5.3
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.1
  - werkzeug=2.1.2
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - wrapt=1.14.1
  - xarray=2022.3.0
  - xerces-c=3.2.3
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - xyzservices=2022.4.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.32.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.1.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - anyascii==0.3.1
    - boruta==0.3
    - colour==0.1.5
    - contractions==0.1.72
    - docopt==0.6.2
    - dtreeviz==1.3.6
    - geofeather==0.3.0
    - iniconfig==1.1.1
    - joypy==0.2.6
    - jupytext==1.13.8
    - kneed==0.7.0
    - langdetect==1.0.9
    - lightgbm==3.3.2
    - markdown-it-py==2.1.0
    - matplotlib-scalebar==0.8.1
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.1
    - num2words==0.5.10
    - py==1.11.0
    - pyahocorasick==1.4.4
    - pytest==7.1.2
    - scikit-posthocs==0.7.0
    - smopy==0.0.8
    - textsearch==0.0.21
    - top2vec==1.0.27
    - unidecode==1.3.4
    - wordcloud==1.8.1
