Executing the command: conda env export -n base
name: base
channels:
  - pyviz
  - conda-forge
dependencies:
  - access=1.1.8
  - affine=2.3.1
  - alembic=1.8.1
  - altair=4.2.0
  - amply=0.1.5
  - ansi2html=1.8.0
  - anyio=3.6.1
  - aom=3.3.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arviz=0.11.1
  - astroid=2.12.10
  - asttokens=2.0.5
  - async_generator=1.10
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - autopep8=1.5.7
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-requests-auth=0.4.2
  - babel=2.10.3
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - black=22.8.0
  - blas=2.115
  - blas-devel=3.9.0
  - bleach=5.0.1
  - blinker=1.4
  - blosc=1.21.1
  - bokeh=2.4.3
  - boto3=1.24.79
  - botocore=1.27.79
  - bottleneck=1.3.5
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.2.0
  - ca-certificates=2022.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - catalogue=2.0.8
  - catboost=1.0.6
  - certifi=2022.6.15
  - certipy=0.1.3
  - cffi=1.15.1
  - cfitsio=4.1.0
  - cftime=1.6.2
  - charls=2.3.4
  - charset-normalizer=2.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.1.0
  - clustergram=0.6.0
  - cmake=3.19.4
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - colorama=0.4.5
  - conda=4.13.0
  - conda-package-handling=1.8.1
  - configurable-http-proxy=4.5.1
  - contextily=1.2.0
  - cryptography=37.0.4
  - curl=7.83.1
  - cycler=0.11.0
  - cymem=2.0.6
  - cython=0.29.30
  - cython-blis=0.7.8
  - cytoolz=0.12.0
  - dash=2.6.1
  - dask=2022.7.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - descartes=1.1.0
  - dill=0.3.5.1
  - distributed=2022.7.0
  - docutils=0.19
  - entrypoints=0.4
  - esda=2.4.3
  - et_xmlfile=1.0.1
  - executing=0.8.3
  - expat=2.4.9
  - fastprogress=1.0.3
  - feather-format=0.4.1
  - fiona=1.8.21
  - flake8=3.9.2
  - flask=2.2.2
  - flask-compress=1.13
  - flit-core=3.7.1
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.34.4
  - freetype=2.10.4
  - freexl=1.0.6
  - fribidi=1.0.10
  - fsspec=2022.5.0
  - gcc_impl_linux-64=10.4.0
  - gcc_linux-64=10.4.0
  - gdal=3.5.1
  - gdk-pixbuf=2.42.8
  - gensim=4.2.0
  - geographiclib=1.52
  - geopandas=0.11.1
  - geopandas-base=0.11.1
  - geopy=2.2.0
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giddy=2.3.3
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - graphite2=1.3.13
  - graphviz=5.0.0
  - greenlet=1.1.2
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=10.4.0
  - gxx_linux-64=10.4.0
  - h5py=3.7.0
  - harfbuzz=5.1.0
  - hdbscan=0.8.28
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - htmlmin=0.1.12
  - icecream=2.1.3
  - icu=70.1
  - idna=3.3
  - imagecodecs=2022.2.22
  - imagehash=4.3.0
  - imageio=2.19.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.8.0
  - inequality=1.0.0
  - ipykernel=6.15.1
  - ipyleaflet=0.17.1
  - ipympl=0.9.2
  - ipyparallel=8.4.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - isort=5.10.1
  - itsdangerous=2.1.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.5
  - jsonlines=1.2.0
  - jsonschema=4.7.2
  - jupyter-dash=0.4.2
  - jupyter-lsp=1.5.1
  - jupyter-lsp-python=1.5.1
  - jupyter-server-mathjax=0.2.6
  - jupyter_bokeh=3.0.5
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - jupyter_telemetry=0.1.0
  - jupyterhub=2.3.1
  - jupyterhub-base=2.3.1
  - jupyterlab=3.4.3
  - jupyterlab-geojson=3.2.0
  - jupyterlab-variableinspector=3.0.9
  - jupyterlab_code_formatter=1.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.15.0
  - jupyterlab_widgets=3.0.3
  - jxrlib=1.1
  - kealib=1.4.15
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - langcodes=3.3.0
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - legendgram=0.0.3
  - lerc=3.0
  - llvm-openmp=14.0.4
  - llvmlite=0.38.1
  - locket=1.0.0
  - lxml=4.9.1
  - lz4=4.0.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mako=1.2.1
  - mamba=0.24.0
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mercantile=1.2.1
  - mgwr=2.1.2
  - missingno=0.4.2
  - mistune=0.8.4
  - momepy=0.5.4
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - msgpack-python=1.0.4
  - multimethod=1.4
  - munch=2.5.0
  - munkres=1.1.4
  - murmurhash=1.0.8
  - mypy_extensions=0.4.3
  - nbclassic=0.4.3
  - nbclient=0.6.6
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbdime=3.1.1
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf4=1.6.0
  - networkx=2.8.6
  - nltk=3.6.7
  - nodejs=17.9.0
  - nomkl=1.0
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - nspr=4.32
  - nss=3.78
  - numba=0.55.2
  - numexpr=2.8.3
  - numpy=1.22.4
  - oauthlib=3.2.0
  - openblas=0.3.20
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=1.1.1q
  - orc=1.7.6
  - osmnx=1.2.2
  - packaging=21.3
  - palettable=3.3.0
  - pamela=1.0.0
  - pandas=1.4.3
  - pandas-profiling=3.3.0
  - pandoc=2.18
  - pandocfilters=1.5.0
  - pango=1.50.9
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.10.1
  - pathy=0.6.2
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - phik=0.12.2
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - platformdirs=2.5.2
  - plotly=5.10.0
  - pluggy=1.0.0
  - pointpats=2.2.0
  - polyline=1.4.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - preshed=3.0.7
  - proj=9.0.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - protobuf=3.20.1
  - psutil=5.9.1
  - psycopg2=2.9.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.6.0
  - pure_eval=0.2.2
  - pyarrow=9.0.0
  - pybind11-abi=4
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pycurl=7.45.1
  - pydantic=1.9.2
  - pydocstyle=6.1.1
  - pyflakes=2.3.1
  - pygeos=0.13
  - pygments=2.12.0
  - pygpu=0.7.6
  - pyjwt=2.4.0
  - pykrige=1.6.1
  - pylint=2.15.3
  - pymc3=3.9.3
  - pynndescent=0.5.7
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.0
  - pyrsistent=0.18.1
  - pysal=2.7.0
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.10.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python-graphviz=0.20.1
  - python-json-logger=2.0.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.1
  - python-tzdata=2022.2
  - python_abi=3.10
  - pytoolconfig=1.2.2
  - pytz=2022.1
  - pytz-deprecation-shim=0.1.0.post0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - quantecon=0.5.3
  - quilt3=5.0.0
  - rasterio=1.3.2
  - rasterstats=0.17.0
  - re2=2022.06.01
  - readline=8.1.2
  - regex=2022.9.13
  - reproc=14.2.3
  - requests=2.28.1
  - requests-futures=1.0.0
  - retrying=1.3.3
  - rhash=1.4.3
  - rope=1.3.0
  - rtree=1.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.15.80
  - rvlib=0.0.6
  - s2n=1.0.10
  - s3transfer=0.6.0
  - scikit-image=0.19.3
  - scikit-learn=1.1.1
  - scipy=1.9.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - segregation=2.3.1
  - send2trash=1.8.0
  - setuptools=63.2.0
  - shapely=1.8.4
  - shellingham=1.5.0
  - simplejson=3.17.6
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=3.0.5
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - spacy=3.4.1
  - spacy-legacy=3.0.10
  - spacy-loggers=1.0.3
  - spaghetti=1.6.6
  - spglm=1.0.8
  - spint=1.0.7
  - splot=1.1.5.post1
  - spopt=0.4.1
  - spreg=1.2.4
  - spvcm=0.3.0
  - sqlalchemy=1.4.39
  - sqlite=3.39.1
  - srsly=2.4.4
  - stack_data=0.3.0
  - statsmodels=0.13.2
  - sympy=1.10.1
  - sysroot_linux-64=2.12
  - tabulate=0.8.10
  - tangled-up-in-unicode=0.2.0
  - tbb=2021.5.0
  - tblib=1.7.0
  - tenacity=8.1.0
  - terminado=0.15.0
  - textblob=0.15.3
  - theano=1.0.5
  - thinc=8.1.0
  - threadpoolctl=3.1.0
  - tifffile=2022.5.4
  - tiledb=2.9.5
  - tinycss2=1.1.1
  - tobler=0.9.0
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.4
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.3.0
  - traittypes=0.2.1
  - typer=0.4.2
  - typing=3.10.0.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzcode=2022c
  - tzdata=2022a
  - tzlocal=4.2
  - ujson=5.5.0
  - umap-learn=0.5.3
  - unicodedata2=14.0.0
  - urllib3=1.26.10
  - visions=0.7.5
  - wasabi=0.10.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.3
  - werkzeug=2.2.2
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - wrapt=1.14.1
  - xarray=2022.6.0
  - xerces-c=3.2.3
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - xyzservices=2022.9.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.32.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.2.0
  - zipp=3.8.0
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
    - anyascii==0.3.1
    - boruta==0.3
    - colour==0.1.5
    - contractions==0.1.72
    - docopt==0.6.2
    - dtreeviz==1.3.7
    - fastai==1.0.61 # Huanfa's QM
    - geofeather==0.3.0
    - gurobipy==9.5.1 # Huanfa's QM
    - iniconfig==1.1.1
    - joypy==0.2.6
    - jupytext==1.14.1
    - kneed==0.8.1
    - langdetect==1.0.9
    - lightgbm==3.3.2
    - markdown-it-py==2.1.0
    - matplotlib-scalebar==0.8.1
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.2
    - num2words==0.5.12
    - pulp==2.6.0 # Huanfa's QM
    - py==1.11.0
    - pyahocorasick==1.4.4
    - pytest==7.1.3
    - rfpimp==1.3.7
    - scikit-posthocs==0.7.0
    - sklearn-som==1.1.0
    - smopy==0.0.8
    - textsearch==0.0.24
    - top2vec==1.0.27
    - unidecode==1.3.4
    - wordcloud==1.8.2.2
