write_files:
    - path: /etc/rc.local
      permissions: "0755"
      owner: root
      content: |
          #!/bin/bash
          # vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
          # Specify the image that we want to install
          IMAGE_NM='{IMAGE_NM}'
          # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          wait-for-docker
          echo -e "\n ******* \n\n Removing existing containers..."
          #----
          # Delete any processes from previous startup
          echo -e "Running cleanup script..."
          CID=$(docker ps -aq)
          if [ -z "$CID" ]
          then
            echo -e "No docker containers found"
          else
            IFS=$'\n' CIDS=($CID)
            for i in "${CIDS[@]}"
            do
              RM=$(docker rm -f $i)
            done
          fi
          #----
          # Check if we have even pulled the images!
          # and pull it if we haven't.
          IMGS=$(docker images "$DOCKER_IMG")

          # Split return from `docker images` by newline
          # and discard the header output
          IFS=$'\n' IIDS=($IMGS)
          IIDS=("${IIDS[@]:1}")

          # If we don't find an image then pull it, 
          # if we do find an image then provide basic 
          # information about it (useful for debugging)
          if [ -z "$IIDS" ]
          then
            echo -e "======================================="
            echo -e "No docker image matching $DOCKER_IMG found..."
            echo -e "......................................."
            echo -e "   Pulling $DOCKER_IMG..."
            docker pull -q "$DOCKER_IMG"
            echo -e "   Done pulling $DOCKER_IMG..."
            echo -e "======================================="
          else
            for i in "${IIDS[@]}"
            do
              echo -e "======================================="
              echo -e "Found $DOCKER_IMG image..."
              echo -e "......................................."
              read VAL <<< $(echo $i | awk -F '[[:space:]][[:space:]]+' '{ printf ("%s\t%s\t%s", $3, $4, $5) }')
              IFS=$'\t' VALS=($VAL)
              echo -e "   Image ID: ${VALS[0]}"
              echo -e "    Created: ${VALS[1]}"
              echo -e "       Size: ${VALS[2]}"
              echo -e "======================================="
            done
          fi
          #----
          # Create mount points
          echo -e "Creating mount points..."
          mkdir -p /home/rancher/data
          mount.vboxsf rancheros /home/rancher/data -o uid=1100
          #mount data /home/rancher/data -o uid=1100
          #----
          # Start up the container
          echo -e "******* \n\n Starting container..."
          docker run -p 8888:8888 \
                     -p 8787:8787 \
                     -p 4000:4000 \
                     -d \
                     --user root -e NB_UID=1100 -e NB_GID=1100 \
                     -v /home/rancher/data:/home/jovyan/work \
                     "$DOCKER_IMG" \
                     start.sh jupyter lab \
                     --LabApp.password='{JUPYTER_PWD}'
          echo -e "******* "
          echo -e "Container available at http://localhost:8888 "
          echo -e "******* "

